try{;(function(){var aC=window._vwo_code;if(aC){window._vwo_j_e=window._vwo_j_e||0;if(window._vwo_j_e==1){window._vwo_mt="dupCode";clearTimeout(window._vwo_settings_timer);if(window.VWO&&window.VWO._&&window.VWO._.bIE){window._vwo_code.finish()}return}if(window._vwo_j_e==-1){window._vwo_j_e=1}}window._vwo_mt="live";try{window._vwo_tm="";var getMode=function(e){var n;if(window.name.indexOf(e)>-1){n=window.name}else{n=window.location.search.match("_vwo_m=([^&]*)");n=n&&n[1]}return n&&JSON.parse(decodeURIComponent(n))};if(window.name.indexOf("_vis_heatmap")>-1||window.name.indexOf("_vis_editor")>-1||getMode("_vwo_cc")||window.name.indexOf("_vis_preview")>-1){window._vwo_mt=window.name}else if(window._vwo_tm.length){window._vwo_mt=window._vwo_tm}else if(location.href.indexOf("_vis_opt_preview_combination")!==-1&&location.href.indexOf("_vis_test_id")!==-1){window._vwo_mt="sharedPreview"}if(window._vwo_mt!=="live"){if(!getMode("_vwo_cc")){_vwo_code.load('https://dev.visualwebsiteoptimizer.com/j.php?mode=' + encodeURIComponent(window._vwo_mt) + '&a=522615&f=1&u=' + encodeURIComponent(window._vis_opt_url||document.URL));}else{(function(){window._vwo_code&&window._vwo_code.finish();_vwo_ccc={u:"/j.php?a=522615&u=https%3A%2F%2Fwww.bottomline.com%2Fapac%2Fnewsroom%2Fevents&f=1&r=0.07984246773730264"};var s=document.createElement("script");s.src="https://app.vwo.com/visitor-behavior-analysis/dist/codechecker/cc.min.js?r="+Math.random();document.head.appendChild(s)})()}}}catch(e){var b=new Image;b.src="https://dev.visualwebsiteoptimizer.com/e.gif?s=mode_det&e="+encodeURIComponent(e&&e.stack&&e.stack.substring(0,1e3));aC&&window._vwo_code.finish()}})();if(window._vwo_mt==='live'){window.VWO=window.VWO||[];window.VWO.push(['fetchPCSettings']);;window.VWO = window.VWO || []; window.VWO.push(['modifyClickPauseTime', { time: 0 }]);_vwo_code.sT=_vwo_code.finished();(function(c,a,e,d,b,z){function f(a,b,d){e.cookie=a+"="+b+"; expires="+new Date(864e5*d+ +new Date).toGMTString()+"; domain="+c+"; path=/"}-1==e.cookie.indexOf("_vis_opt_out")&&-1==d.location.href.indexOf("vwo_opt_out=1")&&(a=e.cookie.replace(/(?:(?:^|.*;\s*)_vwo_uuid_v2\s*=\s*([^;]*).*$)|^.*$/,"$1")||a,a=a.split("|"),b=new Image,c=d.location.hostname||c,b.src="https://dev.visualwebsiteoptimizer.com/v.gif?cd="+(window._vis_opt_cookieDays||0)+"&a=522615&d="+encodeURIComponent(c)+"&u="+a[0]+"&h="+a[1]+"&t="+z+"&r="+Math.random(),d.vwo_iehack_queue=[b],f("_vwo_uuid_v2",a.join("|"),366))})("bottomline.com","DDB17E895BACB8D8188A55F6D20CDDF0C|469ce9514190e1f401d01f25a8a8a3b6",document,window,0,_vwo_code.sT);var _vwo_acc_id=522615;
clearTimeout(_vwo_settings_timer);_vwo_exp_ids=[],_vwo_exp={};window.VWO=window.VWO||[];
window.VWO.data={"noSS":false,"pc":{"a":0,"t":0},"url":{},"rp":60,"ts":1618066097};_vwo_exp_ids.push('3');_vwo_exp['3']={"version":2,"clickmap":0,"globalCode":{},"type":"ANALYZE_HEATMAP","status":"RUNNING","pc_traffic":100,"name":"Heatmap","manual":false,"main":true,"urlRegex":"^.*$","exclude_url":"^https\\:\\\/\\\/bottomline\\.com\\\/uk\\\/?(?:[\\?#].*)?$|^https\\:\\\/\\\/bottomline\\.com\\\/us\\\/?(?:[\\?#].*)?$|^https\\:\\\/\\\/bottomline\\.com\\\/apac\\\/?(?:[\\?#].*)?$","multiple_domains":0,"segment_code":"true","ss":null,"ibe":0,"sections":{"1":{"path":"","variations":{"1":""}}},"combs":{"1":1},"comb_n":{"1":"website"},"goals":{"1":{"urlRegex":"^.*$","excludeUrl":"","type":"ENGAGEMENT"}}};window._vwo_pa=window._vwo_pa || {};_vwo_exp_ids.push('4');_vwo_exp['4']={"version":2,"clickmap":0,"globalCode":{},"type":"ANALYZE_RECORDING","status":"RUNNING","pc_traffic":100,"name":"Visitor Sessions Recorded","manual":false,"main":true,"aK":1,"bl":"","wl":"","urlRegex":"^.*$","exclude_url":"","multiple_domains":0,"segment_code":"true","ss":null,"ibe":1,"sections":{"1":{"path":"","variations":{"1":""}}},"combs":{"1":1},"comb_n":{"1":"website"},"goals":{"1":{"urlRegex":"^.*$","excludeUrl":"","type":"ENGAGEMENT"}}};var _vwo_style=document.getElementById('_vis_opt_path_hides'),_vwo_css= window._vwo_el_style || '{opacity:0 !important;filter:alpha(opacity=0) !important;background:none !important;}';
if(_vwo_style){_vwo_style.parentNode.removeChild(_vwo_style);}window.VWO.data.vi = window.VWO.data.vi || {"os":"MacOS","de":"Other","br":"Chrome","dt":"desktop"};
window.VWO.push(['enableSPA']);
VWO.load_co=function(a){var b=document.createElement('script');b.src=a;b.crossOrigin='anonymous';b.type='text/javascript';b.innerText;b.onerror=function(){_vwo_code.finish();};document.getElementsByTagName('head')[0].appendChild(b);}
var _vwo_cookieDomain = 'bottomline.com', _vwo_uuid = 'DDB17E895BACB8D8188A55F6D20CDDF0C';_vwo_worker_cb='70faafffa0475802f5ee03ca5ff74179';window._vwo_pa = window._vwo_pa || {};window._vwo_pa.sId = '3D7C64791EA73E76';window.VWO.data.as = "r2.visualwebsiteoptimizer.com";var _vwo_library_timer = setTimeout(function () { _vwo_code.finish()},_vwo_code.library_tolerance());var _vis_opt_file = 'web/djIkdGU6Ny4wOmFzeW5jJWdxdWVyeQ==/tag-935006e0a74143fe2d1c17b60f6a5b26.js',_vis_opt_lib = (typeof _vis_opt_lib=='undefined')?'https://dev.visualwebsiteoptimizer.com/'+_vis_opt_file:_vis_opt_lib;VWO.load_co(_vis_opt_lib);(function() {
VWO._=VWO._||{};
var ctId=+new Date(),dtc=VWO._.dtc={ctId:ctId,js:{},tag:['https://dev.visualwebsiteoptimizer.com/web/djIkYTo0LjA6bm9qcXVlcnksdHI6Ny4w/tag-e8c53274e63ced04874ff922464ca5d7.js']};
dtc.js[ctId]=function(){var cb=function(){setTimeout(function(){for(var i=0; i<VWO._.dtc.tag.length;i++){VWO._.coreLib.lS(VWO._.dtc.tag[i])}}, 1000 )};if(document.readyState=='complete')cb();else window.addEventListener('load', cb)};
dtc.sC=function(){ return _vwo_s().f_e(_vwo_s().dt(),'mobile') };;}
)();VWO._.dtc.tC= function(){ return _vwo_t.cm('eO','js',VWO._.dtc.ctId); };; 
window.VWO = window.VWO || [];
window.VWO.data = window.VWO.data || {};
VWO.data.content={"fns":{"list":{"args":{"1":{}},"vn":1}}};;window.VWO = window.VWO||[];window.VWO._=window.VWO._||{};VWO._.ac=VWO._.ac||{};VWO._.ac.dNdOfst=1000;}}catch(e){_vwo_code.finish();var b=new Image;b.src="https://dev.visualwebsiteoptimizer.com/e.gif?a=522615&s=j.php&e="+encodeURIComponent(e && e.message && e.message.substring(0,1000))}